### ISSUE TITLE
[BUG] Previously selected group shows as selected when adding multiple links back to back but is not actually set after creating a new link

### ISSUE THREAD

**Issue by C4ArtZ** [beromir/Servas#12]
### Bug description:
When I add multiple links after another it shows "1 Group selected", refering to the previous links group. However when the link is created, it does not actually end up in the "selected" group.

It seems as if opening the "Select a group" dialog somehow updates the group property even clicking "cancel" immediately.

### Steps to reproduce:
1. Click "New Link"
2. Add URL
3. Select a group
4. Click "Create Link"
5. Click "New Link" again
6. Add URL
7. Click "Create Link"

### Expected behavior:
The previous group selection should either not used when creating a new link or be set without opening the "Select a group" dialog.

**Comment by beromir** [comment]
Thank you for the bug report.  
The function to clear the groups was already there, but I forgot to call it.  
The bug is now fixed in the new version.
