### ISSUE TITLE
Disable registration

### ISSUE THREAD

**Issue by mind-overflow** [beromir/Servas#13]
Hello!
I was wondering if there was a feature (or if it'd be possible to add such feature) to prevent new users from registering, eg. by setting an env variable (`DISABLE_REGISTRATION=true`), so that we could protect our private instances from other people.   
  
Thanks!

**Comment by beromir** [comment]
Thank you for the request.  
This feature is definitely a good idea to protect your instances.

With the new version you can disable the registration page:
First pull the new image, place `SERVAS_ENABLE_REGISTRATION=false` in the `.env` file and restart the container.
