### ISSUE TITLE
Show TOTP token as text next to QR code

### ISSUE THREAD

**Issue by pitah81** [beromir/Servas#19]
Would it be possible to also show TOTP token beneath the QR code as to be able to add it to password managers that has TOTP-support but that don't handle QR scanning?

**Comment by beromir** [comment]
Thank you for the request. This would be a good improvement.
I will work on it later.

PR in the Jetsream repo: https://github.com/laravel/jetstream/pull/1008

**Comment by beromir** [comment]
The setup key is now displayed along with the QR code when you set up 2FA.
