### ISSUE TITLE
Provide feedback in UI when password is too short

### ISSUE THREAD

**Issue by omnisci3nce** [beromir/Servas#21]
I was not sure why nothing was happening when I clicked the "Register" button on the `/register` page form.

I realised later that I needed to make my password longer in order for it to work.
Some small validation or error state below for form input on the front-end would be helpful. I could potentially try and contribute this if you'd like?

Nice clean UI by the way.

**Comment by beromir** [comment]
Thank you for the report.
The error messages of the form fields are now displayed.
I'm glad you like the UI and feel free to open PRs if you want to contribute to the project.

**Comment by omnisci3nce** [comment]
I honestly struggled to get the project setup and running. Not too familiar with the PHP ecosystem.
