### ISSUE TITLE
API Enhancement Request

### ISSUE THREAD

**Issue by imlezz** [beromir/Servas#27]
Hi there,

Is it possible to have the Chrome plugin prompt for Group and Media Type while adding the links thru the extension? 

Currently it just adds the link without any tags,groups or media type info which kinda add additional step to saving links since after adding the links one needs to go back and edit them manually to align them to respective groups/media type/tags.

Thanks!

**Comment by beromir** [comment]
Thank you for the feature request.
That is definitely on my list. But first I want to finish some other functions.

I have a question since you mentioned it. Do you use Media Types? I'm currently thinking about removing this feature since I don't use it and you can accomplish the same thing with tags. I would appreciate your feedback on this issue.

**Comment by imlezz** [comment]
Thank you for your quick response. If I understood correctly, the media type is only available when I use the "Later" function within the portal while saving a bookmark. Am I correct? If this is true then you can certainly remove the media type and replace it with tags.

The ones that I foresee using heavily are the "groups" and "tags".

Also, if there will be a possibility to capture the favicon while saving the bookmarks, it will be amazing.

Thanks for working on this tool. It will surely help me replace my browser bookmarks.

Have a nice day.

**Comment by beromir** [comment]
Hi,
there is now a new extension for Firefox and Chrome, that supports overriding the title and adding tags and groups. It is now also available in the official stores.
Make sure to update Servas to v0.4.1 to be able to use the new features.
https://github.com/beromir/servas-extension
