### ISSUE TITLE
.env is a directory

### ISSUE THREAD

**Issue by rasoga** [beromir/Servas#32]
when docker tries to mount the .env file and that file does not exist in the container docker will mount it as a directory.
So when I try to create the keys I get an ErrorException that .env is a directory.

I do not know how this can best be fixed but it would be nice.

**Comment by beromir** [comment]
Sorry, I don't really understand what you are trying to do. Because if you follow the instructions everything should be fine.
Can you explain the steps to reproduce the error so I can check it.

**Comment by rasoga** [comment]
Hi,

so I try to deploy Servas via Portainer / docker compose. I use the following compose.yml:

version: "3.2"
services:
  servas:
    image: beromir/servas:latest
    container_name: servas
    restart: unless-stopped
    networks:
      - nginx-proxy-nw
    volumes:
      - /docker_files/servas/.env:/var/www/html/.env
      - servas-db-sqlite:/var/www/html/database/sqlite
volumes:
  servas-db-sqlite:
networks:
  nginx-proxy-nw:
    external: true

Now, the container starts fine, but when I try to generate the application key, as mentioned in your instructions, I get the error inside the container that ".env is a directory". And thus it cannot get the contents of the file.

![image](https://user-images.githubusercontent.com/29510533/205517820-5ecd4b29-584c-4211-8e71-79eb959acff3.png)

**Comment by jadehawk** [comment]
> Hi,
> 
> so I try to deploy Servas via Portainer / docker compose. I use the following compose.yml:
> 
> version: "3.2" services: servas: image: beromir/servas:latest container_name: servas restart: unless-stopped networks: - nginx-proxy-nw volumes: - /docker_files/servas/.env:/var/www/html/.env - servas-db-sqlite:/var/www/html/database/sqlite volumes: servas-db-sqlite: networks: nginx-proxy-nw: external: true
> 
> Now, the container starts fine, but when I try to generate the application key, as mentioned in your instructions, I get the error inside the container that ".env is a directory". And thus it cannot get the contents of the file.
> 
> ![image](https://user-images.githubusercontent.com/29510533/205517820-5ecd4b29-584c-4211-8e71-79eb959acff3.png)

You need to manually create the .env file before running the docker container. 

It would be nice if developer implemented a way for the container to create this file automatically if it doesn't exist when starting the container.  But hasn't happened yet.

**Comment by rasoga** [comment]
Yes, it did indeed work! If you create the .env file before running the container it is mounted as a file. Thank you!
