### ISSUE TITLE
Nested Folders need improvement

### ISSUE THREAD

**Issue by RainerZufahl** [beromir/Servas#33]
This app is the only one for bookmarks I could find that supports nested groups, and I think it's a very underrated feature for organization! So thanks for making it an option in the first place.

Sadly, using the nested folders as of now is a little painful. Biggest issue is that creating sub-groups is way more effort than need be. You have to select the parent group for every single entry you want to create. Instead, the currently active group should be the parent group by default when creating a new group using the text input field. This methodology should also apply when creating new links - auto select the currently active group.

If this either goes against your vision for the app or is currently too difficult to implement, I'd ask of you to at least not reset the selected group after creating one. While that won't make creating multiple sub-groups more intuitive, at least it'll be quite a bit faster.

I also thought it might be nice to have a group tree to the side of the view, though that is very much an opinion.

**Comment by beromir** [comment]
Thank you for your feedback, appreciate it.
That is definitely on my list to improve the creation process.
Right now there are no plans to add groups to the sidebar, but I'm currently thinking about redesigning the app and may consider it.
