### ISSUE TITLE
Add a bookmarklet

### ISSUE THREAD

**Issue by RainerZufahl** [beromir/Servas#34]
I'm aware that the browser extension exists. But personally, I don't see the benefit over a simple javascript applet, that would do the same thing without adding a background process in my browser. Additionally, as a bookmarklet is a normal bookmark to a browser, it'll be synced to all connected devices (if sync is set up) and it does not require cross-platform building and testing.

**Comment by beromir** [comment]
Thank you for your request.
I have no experience with bookmarklets and currently have no plans to offer them.
But you are welcome to write it yourself. Maybe later I will offer an official bookmarklet.
