### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by beromir** [beromir/Servas#5]

**Comment by burkesquires** [comment]
Hello,
I am just finding this tool and upon seeing the mysql requirement was thinking that a SQLite based version would be great. When I think about the overhead of mysql and the increasing capability of SQLite, this project seems like it would benefit greatly from SQLite support. Regards!

**Comment by subatomiq** [comment]
agree fully - i'd also be keen to see SQLite support on this one

**Comment by beromir** [comment]
I have just added support for SQLite. Just take a look at the updated README.  
The Docker version does not currently work with SQLite, but will get an update later.
