### ISSUE TITLE
Update Docker Image

### ISSUE THREAD

**Issue by mephisto3478** [beromir/Servas#53]
Hey!
I really like and appreciate your bookmark management tool, but it's only usable for me if I can create subfolders on the groups view.
Either I am too stupid to create one or the latest release on docker hub (two months ago) hasn't it implemented yet.

Could you update the docker image, so I can deploy it with the latest features?

**Comment by beromir** [comment]
Hey,
this is already possible in the latest Docker Image.
1. Go to the groups page
2. Enter a group name
3. Click "Select group" and select the parent group
4. "Create group"

I'm glad you like the app.

**Comment by mephisto3478** [comment]
Thanks for the quick reply. Kind of a usual procedure but it works and that's what I'm after. :)
