### ISSUE TITLE
Executing 'docker exec -it..'

### ISSUE THREAD

**Issue by Tataukee** [beromir/Servas#72]
I am deploying the instance through Portainer on a Synology NAS.. Is there a way to to run the 2 commands ( migration and generating the key ) always inside Portainer ?

**Comment by beromir** [comment]
I haven't used Portainer, so I can't say much about it. But I found [this](https://docs.portainer.io/user/docker/containers/console), I don't know if it helps you.

**Comment by beromir** [comment]
If you find a way to make it work with Portainer, please let me know so I can update the docs.
