### ISSUE TITLE
feature request: tags in opened link page as tag links

### ISSUE THREAD

**Issue by underwoodblog** [beromir/Servas#74]
When opening a link and go back with clicking on **link** on top of page instead of browser back button, the selected tag is deselected. 

Making the tags in the link page as tag links _(/links?tags[0]=mytag)_ makes it easy to go back fast or select another tag without going bag and select a new one, if the link has multiple tags.

![2023-10-02 10 00 05 c99efd17cd22 Servas_ A self-hosted bookmark management tool  _ Servas](https://github.com/beromir/Servas/assets/25827173/2e08d61d-37b3-4fd8-aa70-2662a24e15f4)

**Comment by beromir** [comment]
Thank you for the suggestion.
In the latest version, the tag badges on the single link pages are now clickable.
Make sure to use the latest Docker image `beromir/servas:latest`.
