### ISSUE TITLE
Feature Request: Create group dialog automatically selects the current group if not at top level

### ISSUE THREAD

**Issue by scomoletti** [beromir/Servas#78]
Would it be possible to have the 'create group' dialog automatically select the current group if the user is not displaying the top level? This would greatly simplify the process of creating nested groups.

**Comment by beromir** [comment]
Thank you for the suggestion.
This is already on my list. I'll let you know when it's ready.

**Comment by beromir** [comment]
In the latest version, the group dialog automatically sets the current group as parent group.
