### ISSUE TITLE
Feature Request: Guest Landing Page

### ISSUE THREAD

**Issue by ghostbuster1002** [beromir/Servas#82]
A way to show the landing page to Guests or not signed in Users. I had a use case where I want to share my bookmarks page with my friends but I do not want them to have a account. Is that possible? For reference LinkAce does this.

**Comment by beromir** [comment]
Thank you, this would be a nice feature to have also in Servas. I think this would best fit for groups. So you can share a specific group with a public link, without exposing all your links.
