### ISSUE TITLE
Feature Request: Ungrouped / Untagged items

### ISSUE THREAD

**Issue by TimoReusch** [beromir/Servas#83]
I personally organize everything into groups, so I think two new tabs in the sidebar would make sense: ungrouped links and untagged links. This comes in handy if you just hit "safe" in the Browser extension with the intention to categorize further later on.

**Comment by beromir** [comment]
This is a great suggestion. You can already list untagged links using the button in the tag filter modal. I will also add a way to show ungrouped links, something like an inbox view.

**Comment by beromir** [comment]
There is now an inbox view that shows untagged and ungrouped links.
