### ISSUE TITLE
[FR] Improve the extension and api for saving links with title and tags

### ISSUE THREAD

**Issue by sherlcok314159** [beromir/Servas#89]
Since Firefox extensions can only add URL, this can be inconvenient. This should be fine if the extension can add a title and tags.

Also, the API seems to accept only the URL. Hope this can also support for adding a title and tags.

**Comment by beromir** [comment]
You are right, at the moment titles and tags cannot be added via the API. But that is already on my list.

**Comment by beromir** [comment]
Sorry, no update yet. I wish it was ready already, but I can't say when it will be implemented.

**Comment by sherlcok314159** [comment]
That is ok. Just take your time. :-)

**Comment by beromir** [comment]
Hi,
there is now a new extension for Firefox and Chrome, that supports overriding the title and adding tags and groups. It is now also available in the official stores.
Make sure to update Servas to v0.4.1 to be able to use the new features.
https://github.com/beromir/servas-extension

**Comment by sherlcok314159** [comment]
Does it support self-hosted such as `http://domain_name:port`? I upgraded my servas and something went wrong.

**Comment by beromir** [comment]
Do you get any errors with `docker logs servas`?

**Comment by sherlcok314159** [comment]
Nope. It just throwed out there was an error. I also failed to find log in the developer console. I use firefox. Is there a possibility that firefox blocks the extension from visiting HTTP links?
